const movies = [
    { title: "The Birth of a Nation", year: 1915 },
    { title: "20,000 Leagues Under the Sea", year: 1916 },
    { title: "Intolerance", year: 1916 },
    { title: "The Kid", year: 1921 },
    { title: "Sherlock Jr.", year: 1924 },
    { title: "The Gold Rush", year: 1925 },
    { title: "The General", year: 1926 },
    { title: "The Jazz Singer", year: 1927 },
    { title: "Steamboat Bill, Jr.", year: 1928 },
    { title: "The Cameraman", year: 1928 },
    { title: "All Quiet on the Western Front", year: 1930 },
    { title: "City Lights", year: 1931 },
    { title: "Dracula", year: 1931 },
    { title: "Frankenstein", year: 1931 },
    { title: "Little Caesar", year: 1931 },
    { title: "Duck Soup", year: 1933 },
    { title: "King Kong", year: 1933 },
    { title: "The Invisible Man", year: 1933 },
    { title: "Bride of Frankenstein", year: 1935 },
    { title: "Modern Times", year: 1936 },
    { title: "Gone with the Wind", year: 1939 },
    { title: "Mr. Smith Goes to Washington", year: 1939 },
    { title: "The Wizard of Oz", year: 1939 },
    { title: "Rebecca", year: 1940 },
    { title: "The Grapes of Wrath", year: 1940 },
    { title: "The Great Dictator", year: 1940 },
    { title: "Citizen Kane", year: 1941 },
    { title: "The Maltese Falcon", year: 1941 },
    { title: "Casablanca", year: 1942 },
    { title: "Shadow of a Doubt", year: 1943 },
    { title: "Double Indemnity", year: 1944 },
    { title: "Gaslight", year: 1944 },
    { title: "It's a Wonderful Life", year: 1946 },
    { title: "Notorious", year: 1946 },
    { title: "Miracle on 34th Street", year: 1947 },
    { title: "White Heat", year: 1949 },
    { title: "All About Eve", year: 1950 },
    { title: "Sunset Boulevard", year: 1950 },
    { title: "The African Queen", year: 1951 },
    { title: "The Day the Earth Stood Still", year: 1951 },
    { title: "The Thing from Another World", year: 1951 },
    { title: "High Noon", year: 1952 },
    { title: "Singin' in the Rain", year: 1952 },
    { title: "The War of the Worlds", year: 1953 },
    { title: "A Star Is Born", year: 1954 },
    { title: "Rear Window", year: 1954 },
    { title: "Seven Samurai", year: 1954 },
    { title: "Rebel Without a Cause", year: 1955 },
    { title: "Invasion of the Body Snatchers", year: 1956 },
    { title: "The Ten Commandments", year: 1956 },
    { title: "12 Angry Men", year: 1957 },
    { title: "Jailhouse Rock", year: 1957 },
    { title: "Paths of Glory", year: 1957 },
    { title: "The Bridge on the River Kwai", year: 1957 },
    { title: "Vertigo", year: 1958 },
    { title: "Anatomy of a Murder", year: 1959 },
    { title: "Ben-Hur", year: 1959 },
    { title: "North by Northwest", year: 1959 },
    { title: "Some Like It Hot", year: 1959 },
    { title: "Psycho", year: 1960 },
    { title: "Spartacus", year: 1960 },
    { title: "The Magnificent Seven", year: 1960 },
    { title: "Breakfast at Tiffany's", year: 1961 },
    { title: "West Side Story", year: 1961 },
    { title: "Dr. No", year: 1962 },
    { title: "How the West Was Won", year: 1962 },
    { title: "Lawrence of Arabia", year: 1962 },
    { title: "The Manchurian Candidate", year: 1962 },
    { title: "To Kill a Mockingbird", year: 1962 },
    { title: "From Russia with Love", year: 1963 },
    { title: "The Birds", year: 1963 },
    { title: "The Pink Panther", year: 1963 },
    { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964 },
    { title: "Goldfinger", year: 1964 },
    { title: "Mary Poppins", year: 1964 },
    { title: "My Fair Lady", year: 1964 },
    { title: "The Sound of Music", year: 1965 },
    { title: "Seconds", year: 1966 },
    { title: "The Good, the Bad and the Ugly", year: 1966 },
    { title: "Who's Afraid of Virginia Woolf?", year: 1966 },
    { title: "Bonnie and Clyde", year: 1967 },
    { title: "The Graduate", year: 1967 },
    { title: "The Producers", year: 1967 },
    { title: "2001: A Space Odyssey", year: 1968 },
    { title: "Bullitt", year: 1968 },
    { title: "Night of the Living Dead", year: 1968 },
    { title: "Planet of the Apes", year: 1968 },
    { title: "Rosemary's Baby", year: 1968 },
    { title: "Butch Cassidy and the Sundance Kid", year: 1969 },
    { title: "Easy Rider", year: 1969 },
    { title: "The Wild Bunch", year: 1969 },
    { title: "M*A*S*H", year: 1970 },
    { title: "Patton", year: 1970 },
    { title: "Wanda", year: 1970 },
    { title: "A Clockwork Orange", year: 1971 },
    { title: "Dirty Harry", year: 1971 },
    { title: "Shaft", year: 1971 },
    { title: "Sweet Sweetback's Baadasssss Song", year: 1971 },
    { title: "The French Connection", year: 1971 },
    { title: "Willy Wonka & the Chocolate Factory", year: 1971 },
    { title: "Cabaret", year: 1972 },
    { title: "Super Fly", year: 1972 },
    { title: "The Godfather", year: 1972 },
    { title: "American Graffiti", year: 1973 },
    { title: "Badlands", year: 1973 },
    { title: "The Exorcist", year: 1973 },
    { title: "The Sting", year: 1973 },
    { title: "Blazing Saddles", year: 1974 },
    { title: "Chinatown", year: 1974 },
    { title: "The Conversation", year: 1974 },
    { title: "The Godfather Part II", year: 1974 },
    { title: "The Texas Chain Saw Massacre", year: 1974 },
    { title: "Young Frankenstein", year: 1974 },
    { title: "Jaws", year: 1975 },
    { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
    { title: "The Rocky Horror Picture Show", year: 1975 },
    { title: "All the President's Men", year: 1976 },
    { title: "Rocky", year: 1976 },
    { title: "Taxi Driver", year: 1976 },
    { title: "Annie Hall", year: 1977 },
    { title: "Close Encounters of the Third Kind", year: 1977 },
    { title: "Eraserhead", year: 1977 },
    { title: "Saturday Night Fever", year: 1977 },
    { title: "Star Wars", year: 1977 },
    { title: "Days of Heaven", year: 1978 },
    { title: "Grease", year: 1978 },
    { title: "Halloween", year: 1978 },
    { title: "Superman", year: 1978 },
    { title: "The Deer Hunter", year: 1978 },
    { title: "Alien", year: 1979 },
    { title: "Apocalypse Now", year: 1979 },
    { title: "Fame", year: 1980 },
    { title: "Raging Bull", year: 1980 },
    { title: "The Blues Brothers", year: 1980 },
    { title: "The Elephant Man", year: 1980 },
    { title: "The Empire Strikes Back", year: 1980 },
    { title: "The Shining", year: 1980 },
    { title: "Raiders of the Lost Ark", year: 1981 },
    { title: "Blade Runner", year: 1982 },
    { title: "E.T. the Extra-Terrestrial", year: 1982 },
    { title: "Star Trek II: The Wrath of Khan", year: 1982 },
    { title: "The Thing", year: 1982 },
    { title: "Tootsie", year: 1982 },
    { title: "Return of the Jedi", year: 1983 },
    { title: "Scarface", year: 1983 },
    { title: "The Right Stuff", year: 1983 },
    { title: "A Nightmare on Elm Street", year: 1984 },
    { title: "Amadeus", year: 1984 },
    { title: "Beverly Hills Cop", year: 1984 },
    { title: "Ghostbusters", year: 1984 },
    { title: "Purple Rain", year: 1984 },
    { title: "The Terminator", year: 1984 },
    { title: "This Is Spinal Tap", year: 1984 },
    { title: "Back to the Future", year: 1985 },
    { title: "Desperately Seeking Susan", year: 1985 },
    { title: "The Breakfast Club", year: 1985 },
    { title: "The Goonies", year: 1985 },
    { title: "Aliens", year: 1986 },
    { title: "Platoon", year: 1986 },
    { title: "Stand by Me", year: 1986 },
    { title: "Top Gun", year: 1986 },
    { title: "Dirty Dancing", year: 1987 },
    { title: "Full Metal Jacket", year: 1987 },
    { title: "Robocop", year: 1987 },
    { title: "Die Hard", year: 1988 },
    { title: "Hairspray", year: 1988 },
    { title: "My Neighbor Totoro", year: 1988 },
    { title: "Rain Man", year: 1988 },
    { title: "Dead Poets Society", year: 1989 },
    { title: "When Harry Met Sally...", year: 1989 },
    { title: "Dances With Wolves", year: 1990 },
    { title: "Goodfellas", year: 1990 },
    { title: "Home Alone", year: 1990 },
    { title: "Boyz n the Hood", year: 1991 },
    { title: "Terminator 2: Judgment Day", year: 1991 },
    { title: "The Silence of the Lambs", year: 1991 },
    { title: "Thelma & Louise", year: 1991 },
    { title: "Malcolm X", year: 1992 },
    { title: "Unforgiven", year: 1992 },
    { title: "Groundhog Day", year: 1993 },
    { title: "Jurassic Park", year: 1993 },
    { title: "Schindler's List", year: 1993 },
    { title: "The Fugitive", year: 1993 },
    { title: "Forrest Gump", year: 1994 },
    { title: "Léon: The Professional", year: 1994 },
    { title: "Pulp Fiction", year: 1994 },
    { title: "Speed", year: 1994 },
    { title: "The Lion King", year: 1994 },
    { title: "The Shawshank Redemption", year: 1994 },
    { title: "Apollo 13", year: 1995 },
    { title: "Braveheart", year: 1995 },
    { title: "Casino", year: 1995 },
    { title: "GoldenEye", year: 1995 },
    { title: "Heat", year: 1995 },
    { title: "My Family", year: 1995 },
    { title: "Se7en", year: 1995 },
    { title: "The Usual Suspects", year: 1995 },
    { title: "Toy Story", year: 1995 },
    { title: "Fargo", year: 1996 },
    { title: "Mission: Impossible", year: 1996 },
    { title: "The Rock", year: 1996 },
    { title: "L.A. Confidential", year: 1997 },
    { title: "Men in Black", year: 1997 },
    { title: "Titanic", year: 1997 },
    { title: "American History X", year: 1998 },
    { title: "Lock, Stock and Two Smoking Barrels", year: 1998 },
    { title: "Saving Private Ryan", year: 1998 },
    { title: "The Big Lebowski", year: 1998 },
    { title: "The Truman Show", year: 1998 },
    { title: "American Beauty", year: 1999 },
    { title: "Boys Don't Cry", year: 1999 },
    { title: "Fight Club", year: 1999 },
    { title: "The Green Mile", year: 1999 },
    { title: "The Iron Giant", year: 1999 },
    { title: "The Matrix", year: 1999 },
    { title: "The Sixth Sense", year: 1999 },
    { title: "Bamboozled", year: 2000 },
    { title: "Cast Away", year: 2000 },
    { title: "Gladiator", year: 2000 },
    { title: "Memento", year: 2000 },
    { title: "Snatch", year: 2000 },
    { title: "A Beautiful Mind", year: 2001 },
    { title: "Amélie", year: 2001 },
    { title: "Donnie Darko", year: 2001 },
    { title: "Harry Potter and the Sorcerer's Stone", year: 2001 },
    { title: "Monsters, Inc.", year: 2001 },
    { title: "Ocean's Eleven", year: 2001 },
    { title: "Shrek", year: 2001 },
    { title: "Spy Kids", year: 2001 },
    { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
    { title: "Catch Me If You Can", year: 2002 },
    { title: "City of God", year: 2002 },
    { title: "Real Women Have Curves", year: 2002 },
    { title: "Spider-Man", year: 2002 },
    { title: "The Lord of the Rings: The Two Towers", year: 2002 },
    { title: "The Pianist", year: 2002 },
    { title: "Finding Nemo", year: 2003 },
    { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003 },
    { title: "The Lord of the Rings: The Return of the King", year: 2003 },
    { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
    { title: "Million Dollar Baby", year: 2004 },
    { title: "The Incredibles", year: 2004 },
    { title: "The Terminal", year: 2004 },
    { title: "Brokeback Mountain", year: 2005 },
    { title: "Casino Royale", year: 2006 },
    { title: "The Departed", year: 2006 },
    { title: "No Country for Old Men", year: 2007 },
    { title: "Ratatouille", year: 2007 },
    { title: "There Will Be Blood", year: 2007 },
    { title: "Kung Fu Panda", year: 2008 },
    { title: "Slumdog Millionaire", year: 2008 },
    { title: "The Dark Knight", year: 2008 },
    { title: "WALL-E", year: 2008 },
    { title: "Avatar", year: 2009 },
    { title: "Harry Potter and the Half-Blood Prince", year: 2009 },
    { title: "Up", year: 2009 },
    { title: "Inception", year: 2010 },
    { title: "Shutter Island", year: 2010 },
    { title: "The King's Speech", year: 2010 },
    { title: "The Social Network", year: 2010 },
    { title: "Drive", year: 2011 },
    { title: "The Artist", year: 2011 },
    { title: "The Intouchables", year: 2011 },
    { title: "Django Unchained", year: 2012 },
    { title: "Skyfall", year: 2012 },
    { title: "The Avengers", year: 2012 },
    { title: "The Dark Knight Rises", year: 2012 },
    { title: "The Hunger Games", year: 2012 },
    { title: "12 Years a Slave", year: 2013 },
    { title: "Her", year: 2013 },
    { title: "The Wolf of Wall Street", year: 2013 },
    { title: "Gone Girl", year: 2014 },
    { title: "Interstellar", year: 2014 },
    { title: "Inside Out", year: 2015 },
    { title: "Arrival", year: 2016 },
    { title: "Moonlight", year: 2016 },
    { title: "Blade Runner 2049", year: 2017 },
    { title: "The Shape of Water", year: 2017 },
    { title: "Bohemian Rhapsody", year: 2018 },
    { title: "1917", year: 2019 },
    { title: "Joker", year: 2019 },
    { title: "Once Upon a Time in Hollywood", year: 2019 },
    { title: "Parasite", year: 2019 },
    { title: "The Irishman", year: 2019 }
];
