const movies = [
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "The Godfather", year: 1972 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "The Dark Knight", year: 2008 },
  { title: "12 Angry Men", year: 1957 },
  { title: "Schindler’s List", year: 1993 },
  { title: "The Lord of the Rings: The Return of the King", year: 2003 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "The Good, the Bad and the Ugly", year: 1966 },

  { title: "Forrest Gump", year: 1994 },
  { title: "Fight Club", year: 1999 },
  { title: "The Lord of the Rings: The Two Towers", year: 2002 },
  { title: "Inception", year: 2010 },
  { title: "Star Wars: Episode V – The Empire Strikes Back", year: 1980 },
  { title: "The Matrix", year: 1999 },
  { title: "Goodfellas", year: 1990 },
  { title: "One Flew Over the Cuckoo’s Nest", year: 1975 },
  { title: "Seven Samurai", year: 1954 },
  { title: "Se7en", year: 1995 },

  { title: "City of God", year: 2002 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "It’s a Wonderful Life", year: 1946 },
  { title: "Star Wars: Episode IV – A New Hope", year: 1977 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "Spirited Away", year: 2001 },
  { title: "Interstellar", year: 2014 },
  { title: "Parasite", year: 2019 },
  { title: "The Green Mile", year: 1999 },
  { title: "Léon: The Professional", year: 1994 },

  { title: "The Usual Suspects", year: 1995 },
  { title: "Harakiri", year: 1962 },
  { title: "The Lion King", year: 1994 },
  { title: "Back to the Future", year: 1985 },
  { title: "The Pianist", year: 2002 },
  { title: "Terminator 2: Judgment Day", year: 1991 },
  { title: "American History X", year: 1998 },
  { title: "Modern Times", year: 1936 },
  { title: "Gladiator", year: 2000 },
  { title: "The Departed", year: 2006 },

  { title: "Whiplash", year: 2014 },
  { title: "The Prestige", year: 2006 },
  { title: "The Intouchables", year: 2011 },
  { title: "The Dark Knight Rises", year: 2012 },
  { title: "Alien", year: 1979 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "Memento", year: 2000 },
  { title: "Indiana Jones and the Raiders of the Lost Ark", year: 1981 },
  { title: "Django Unchained", year: 2012 },
  { title: "WALL·E", year: 2008 },

  { title: "The Shining", year: 1980 },
  { title: "Avengers: Infinity War", year: 2018 },
  { title: "Oldboy", year: 2003 },
  { title: "Princess Mononoke", year: 1997 },
  { title: "Aliens", year: 1986 },
  { title: "Once Upon a Time in the West", year: 1968 },
  { title: "Coco", year: 2017 },
  { title: "American Beauty", year: 1999 },
  { title: "Braveheart", year: 1995 },
  { title: "Toy Story", year: 1995 },

  { title: "Amadeus", year: 1984 },
  { title: "A Clockwork Orange", year: 1971 },
  { title: "Taxi Driver", year: 1976 },
  { title: "The Social Network", year: 2010 },
  { title: "Full Metal Jacket", year: 1987 },
  { title: "The Grand Budapest Hotel", year: 2014 },
  { title: "Jurassic Park", year: 1993 },
  { title: "The Terminator", year: 1984 },
  { title: "Jaws", year: 1975 },
  { title: "Blade Runner", year: 1982 },

  { title: "Gone with the Wind", year: 1939 },
  { title: "Die Hard", year: 1988 },
  { title: "The Wolf of Wall Street", year: 2013 },
  { title: "No Country for Old Men", year: 2007 },
  { title: "Shutter Island", year: 2010 },
  { title: "The Big Lebowski", year: 1998 },
  { title: "Mad Max: Fury Road", year: 2015 },
  { title: "Dead Poets Society", year: 1989 },
  { title: "Logan", year: 2017 },
  { title: "There Will Be Blood", year: 2007 }
];

{ title: "The Truman Show", year: 1998 },
  { title: "The Sixth Sense", year: 1999 },
  { title: "Groundhog Day", year: 1993 },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
  { title: "The Breakfast Club", year: 1985 },
  { title: "The Princess Bride", year: 1987 },
  { title: "Stand by Me", year: 1986 },
  { title: "Platoon", year: 1986 },
  { title: "Rain Man", year: 1988 },
  { title: "Rocky", year: 1976 },

  { title: "Scarface", year: 1983 },
  { title: "The Exorcist", year: 1973 },
  { title: "The Graduate", year: 1967 },
  { title: "Fargo", year: 1996 },
  { title: "The Thing", year: 1982 },
  { title: "Donnie Darko", year: 2001 },
  { title: "Heat", year: 1995 },
  { title: "Casino", year: 1995 },
  { title: "The Revenant", year: 2015 },
  { title: "Life Is Beautiful", year: 1997 },

  { title: "The Sting", year: 1973 },
  { title: "Network", year: 1976 },
  { title: "Ben-Hur", year: 1959 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "The Elephant Man", year: 1980 },
  { title: "Amélie", year: 2001 },
  { title: "Snatch", year: 2000 },
  { title: "Lock, Stock and Two Smoking Barrels", year: 1998 },
  { title: "The Incredibles", year: 2004 },
  { title: "Finding Nemo", year: 2003 },

  { title: "Inside Out", year: 2015 },
  { title: "Up", year: 2009 },
  { title: "Monsters, Inc.", year: 2001 },
  { title: "Shrek", year: 2001 },
  { title: "Ratatouille", year: 2007 },
  { title: "Howl’s Moving Castle", year: 2004 },
  { title: "My Neighbor Totoro", year: 1988 },
  { title: "The Iron Giant", year: 1999 },
  { title: "The Nightmare Before Christmas", year: 1993 },
  { title: "Kung Fu Panda", year: 2008 },

  { title: "The Hobbit: An Unexpected Journey", year: 2012 },
  { title: "The Hobbit: The Desolation of Smaug", year: 2013 },
  { title: "The Hobbit: The Battle of the Five Armies", year: 2014 },
  { title: "Harry Potter and the Sorcerer’s Stone", year: 2001 },
  { title: "Harry Potter and the Chamber of Secrets", year: 2002 },
  { title: "Harry Potter and the Prisoner of Azkaban", year: 2004 },
  { title: "Harry Potter and the Goblet of Fire", year: 2005 },
  { title: "Harry Potter and the Order of the Phoenix", year: 2007 },
  { title: "Harry Potter and the Half-Blood Prince", year: 2009 },
  { title: "Harry Potter and the Deathly Hallows – Part 1", year: 2010 },

  { title: "Harry Potter and the Deathly Hallows – Part 2", year: 2011 },
  { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003 },
  { title: "Pirates of the Caribbean: Dead Man’s Chest", year: 2006 },
  { title: "Pirates of the Caribbean: At World’s End", year: 2007 },
  { title: "Pirates of the Caribbean: On Stranger Tides", year: 2011 },
  { title: "Pirates of the Caribbean: Dead Men Tell No Tales", year: 2017 },
  { title: "Avatar", year: 2009 },
  { title: "Titanic", year: 1997 },
  { title: "The Hunger Games", year: 2012 },
  { title: "Catching Fire", year: 2013 },

  { title: "Mockingjay – Part 1", year: 2014 },
  { title: "Mockingjay – Part 2", year: 2015 },
  { title: "The Matrix Reloaded", year: 2003 },
  { title: "The Matrix Revolutions", year: 2003 },
  { title: "Edge of Tomorrow", year: 2014 },
  { title: "Minority Report", year: 2002 },
  { title: "The Bourne Identity", year: 2002 },
  { title: "The Bourne Supremacy", year: 2004 },
  { title: "The Bourne Ultimatum", year: 2007 },
  { title: "Skyfall", year: 2012 }

{ title: "Casino Royale", year: 2006 },
  { title: "GoldenEye", year: 1995 },
  { title: "From Russia with Love", year: 1963 },
  { title: "Goldfinger", year: 1964 },
  { title: "Dr. No", year: 1962 },
  { title: "Thunderball", year: 1965 },
  { title: "You Only Live Twice", year: 1967 },
  { title: "On Her Majesty’s Secret Service", year: 1969 },
  { title: "Live and Let Die", year: 1973 },
  { title: "The Spy Who Loved Me", year: 1977 },

  { title: "Raging Bull", year: 1980 },
  { title: "The Deer Hunter", year: 1978 },
  { title: "Unforgiven", year: 1992 },
  { title: "The French Connection", year: 1971 },
  { title: "Butch Cassidy and the Sundance Kid", year: 1969 },
  { title: "Cool Hand Luke", year: 1967 },
  { title: "Chinatown", year: 1974 },
  { title: "The Graduate", year: 1967 },
  { title: "Midnight Cowboy", year: 1969 },
  { title: "Dog Day Afternoon", year: 1975 },

  { title: "The Godfather Part III", year: 1990 },
  { title: "Blade Runner 2049", year: 2017 },
  { title: "Her", year: 2013 },
  { title: "Moonlight", year: 2016 },
  { title: "The Shape of Water", year: 2017 },
  { title: "Birdman", year: 2014 },
  { title: "La La Land", year: 2016 },
  { title: "Gravity", year: 2013 },
  { title: "Slumdog Millionaire", year: 2008 },
  { title: "Million Dollar Baby", year: 2004 },

  { title: "No Country for Old Men", year: 2007 },
  { title: "There Will Be Blood", year: 2007 },
  { title: "The Hurt Locker", year: 2008 },
  { title: "Argo", year: 2012 },
  { title: "Spotlight", year: 2015 },
  { title: "12 Years a Slave", year: 2013 },
  { title: "The King’s Speech", year: 2010 },
  { title: "A Beautiful Mind", year: 2001 },
  { title: "Chicago", year: 2002 },
  { title: "The Artist", year: 2011 },

  { title: "Lincoln", year: 2012 },
  { title: "The Aviator", year: 2004 },
  { title: "The Curious Case of Benjamin Button", year: 2008 },
  { title: "The Theory of Everything", year: 2014 },
  { title: "Bohemian Rhapsody", year: 2018 },
  { title: "The Imitation Game", year: 2014 },
  { title: "Joker", year: 2019 },
  { title: "1917", year: 2019 },
  { title: "Dunkirk", year: 2017 },
  { title: "Arrival", year: 2016 },

  { title: "Ex Machina", year: 2014 },
  { title: "District 9", year: 2009 },
  { title: "Children of Men", year: 2006 },
  { title: "Blade Runner", year: 1982 },
  { title: "Total Recall", year: 1990 },
  { title: "The Fifth Element", year: 1997 },
  { title: "Gattaca", year: 1997 },
  { title: "Star Trek", year: 2009 },
  { title: "Star Trek Into Darkness", year: 2013 },
  { title: "Star Trek Beyond", year: 2016 },

  { title: "Planet of the Apes", year: 1968 },
  { title: "Rise of the Planet of the Apes", year: 2011 },
  { title: "Dawn of the Planet of the Apes", year: 2014 },
  { title: "War for the Planet of the Apes", year: 2017 },
  { title: "The Terminator", year: 1984 },
  { title: "Predator", year: 1987 },
  { title: "Robocop", year: 1987 },
  { title: "Die Hard 2", year: 1990 },
  { title: "Lethal Weapon", year: 1987 },
  { title: "Lethal Weapon 2", year: 1989 }

   { title: "Rocky II", year: 1979 },
  { title: "Rocky III", year: 1982 },
  { title: "Rocky IV", year: 1985 },
  { title: "Rocky Balboa", year: 2006 },
  { title: "First Blood", year: 1982 },
  { title: "Rambo: First Blood Part II", year: 1985 },
  { title: "Rambo III", year: 1988 },
  { title: "Creed", year: 2015 },
  { title: "Creed II", year: 2018 },
  { title: "The Karate Kid", year: 1984 },

  { title: "The Karate Kid Part II", year: 1986 },
  { title: "The Karate Kid Part III", year: 1989 },
  { title: "Rush", year: 2013 },
  { title: "Ford v Ferrari", year: 2019 },
  { title: "The Prestige", year: 2006 },
  { title: "Seabiscuit", year: 2003 },
  { title: "Moneyball", year: 2011 },
  { title: "The Fighter", year: 2010 },
  { title: "Cinderella Man", year: 2005 },
  { title: "Million Dollar Baby", year: 2004 },

  { title: "Ocean’s Eleven", year: 2001 },
  { title: "Ocean’s Twelve", year: 2004 },
  { title: "Ocean’s Thirteen", year: 2007 },
  { title: "The Italian Job", year: 2003 },
  { title: "Heat", year: 1995 },
  { title: "Collateral", year: 2004 },
  { title: "Drive", year: 2011 },
  { title: "Baby Driver", year: 2017 },
  { title: "The Town", year: 2010 },
  { title: "Public Enemies", year: 2009 },

  { title: "Training Day", year: 2001 },
  { title: "Zodiac", year: 2007 },
  { title: "Prisoners", year: 2013 },
  { title: "Gone Girl", year: 2014 },
  { title: "Mystic River", year: 2003 },
  { title: "L.A. Confidential", year: 1997 },
  { title: "The Untouchables", year: 1987 },
  { title: "Serpico", year: 1973 },
  { title: "Donnie Brasco", year: 1997 },
  { title: "Scarface", year: 1983 },

  { title: "The Big Short", year: 2015 },
  { title: "Catch Me If You Can", year: 2002 },
  { title: "The Wolf of Wall Street", year: 2013 },
  { title: "The Departed", year: 2006 },
  { title: "Shutter Island", year: 2010 },
  { title: "Gangs of New York", year: 2002 },
  { title: "Casino", year: 1995 },
  { title: "Mean Streets", year: 1973 },
  { title: "Raging Bull", year: 1980 },
  { title: "Cape Fear", year: 1991 },

  { title: "A Bronx Tale", year: 1993 },
  { title: "The Irishman", year: 2019 },
  { title: "Once Upon a Time in Hollywood", year: 2019 },
  { title: "The Hateful Eight", year: 2015 },
  { title: "Django Unchained", year: 2012 },
  { title: "Inglourious Basterds", year: 2009 },
  { title: "Kill Bill: Vol. 1", year: 2003 },
  { title: "Kill Bill: Vol. 2", year: 2004 },
  { title: "Reservoir Dogs", year: 1992 },
  { title: "Jackie Brown", year: 1997 },

  { title: "The Truman Show", year: 1998 },
  { title: "E.T. the Extra-Terrestrial", year: 1982 },
  { title: "Close Encounters of the Third Kind", year: 1977 },
  { title: "War of the Worlds", year: 2005 },
  { title: "Minority Report", year: 2002 },
  { title: "Catch-22", year: 1970 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "Munich", year: 2005 },
  { title: "Schindler’s List", year: 1993 },
  { title: "The Color Purple", year: 1985 },

  { title: "Jaws 2", year: 1978 },
  { title: "Indiana Jones and the Temple of Doom", year: 1984 },
  { title: "Indiana Jones and the Last Crusade", year: 1989 },
  { title: "Indiana Jones and the Kingdom of the Crystal Skull", year: 2008 },
  { title: "Ready Player One", year: 2018 },
  { title: "Hook", year: 1991 },
  { title: "The Goonies", year: 1985 },
  { title: "Gremlins", year: 1984 },
  { title: "Poltergeist", year: 1982 },
  { title: "Twister", year: 1996 }

{ title: "The Fugitive", year: 1993 },
  { title: "Air Force One", year: 1997 },
  { title: "The Rock", year: 1996 },
  { title: "Con Air", year: 1997 },
  { title: "Face/Off", year: 1997 },
  { title: "Speed", year: 1994 },
  { title: "Heat", year: 1995 },
  { title: "Point Break", year: 1991 },
  { title: "Top Gun", year: 1986 },

  { title: "Mission: Impossible", year: 1996 },
  { title: "Mission: Impossible 2", year: 2000 },
  { title: "Mission: Impossible III", year: 2006 },
  { title: "Mission: Impossible – Ghost Protocol", year: 2011 },
  { title: "Mission: Impossible – Rogue Nation", year: 2015 },
  { title: "Mission: Impossible – Fallout", year: 2018 },
  { title: "Jason Bourne", year: 2016 },
  { title: "The Bourne Legacy", year: 2012 },
  { title: "True Lies", year: 1994 },
  { title: "Bad Boys", year: 1995 },

  { title: "Bad Boys II", year: 2003 },
  { title: "Lethal Weapon 3", year: 1992 },
  { title: "Lethal Weapon 4", year: 1998 },
  { title: "The Mask", year: 1994 },
  { title: "Ace Ventura: Pet Detective", year: 1994 },
  { title: "Dumb and Dumber", year: 1994 },
  { title: "Austin Powers: International Man of Mystery", year: 1997 },
  { title: "Austin Powers: The Spy Who Shagged Me", year: 1999 },
  { title: "Austin Powers in Goldmember", year: 2002 },
  { title: "Ghostbusters", year: 1984 },

  { title: "Ghostbusters II", year: 1989 },
  { title: "Men in Black", year: 1997 },
  { title: "Men in Black II", year: 2002 },
  { title: "Men in Black 3", year: 2012 },
  { title: "Independence Day", year: 1996 },
  { title: "Armageddon", year: 1998 },
  { title: "Deep Impact", year: 1998 },
  { title: "The Day After Tomorrow", year: 2004 },
  { title: "2012", year: 2009 },
  { title: "I Am Legend", year: 2007 },

  { title: "Cast Away", year: 2000 },
  { title: "Forrest Gump", year: 1994 },
  { title: "The Green Mile", year: 1999 },
  { title: "Saving Mr. Banks", year: 2013 },
  { title: "The Blind Side", year: 2009 },
  { title: "Jerry Maguire", year: 1996 },
  { title: "Rain Man", year: 1988 },
  { title: "Big", year: 1988 },
  { title: "A League of Their Own", year: 1992 },
  { title: "The Terminal", year: 2004 },

  { title: "Spider-Man", year: 2002 },
  { title: "Spider-Man 2", year: 2004 },
  { title: "Spider-Man 3", year: 2007 },
  { title: "The Amazing Spider-Man", year: 2012 },
  { title: "The Amazing Spider-Man 2", year: 2014 },
  { title: "Iron Man", year: 2008 },
  { title: "Iron Man 2", year: 2010 },
  { title: "Iron Man 3", year: 2013 },
  { title: "Thor", year: 2011 },
  { title: "Thor: The Dark World", year: 2013 },

  { title: "Thor: Ragnarok", year: 2017 },
  { title: "Captain America: The First Avenger", year: 2011 },
  { title: "Captain America: The Winter Soldier", year: 2014 },
  { title: "Captain America: Civil War", year: 2016 },
  { title: "The Avengers", year: 2012 },
  { title: "Avengers: Age of Ultron", year: 2015 },
  { title: "Avengers: Infinity War", year: 2018 },
  { title: "Avengers: Endgame", year: 2019 },
  { title: "Guardians of the Galaxy", year: 2014 },
  { title: "Guardians of the Galaxy Vol. 2", year: 2017 },

  { title: "Black Panther", year: 2018 },
  { title: "Doctor Strange", year: 2016 },
  { title: "Ant-Man", year: 2015 },
  { title: "Ant-Man and the Wasp", year: 2018 },
  { title: "Captain Marvel", year: 2019 }
];
