const movies = [
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "The Godfather", year: 1972 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "The Dark Knight", year: 2008 },
  { title: "12 Angry Men", year: 1957 },
  { title: "Schindler's List", year: 1993 },
  { title: "The Lord of the Rings: The Return of the King", year: 2003 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "The Good, the Bad and the Ugly", year: 1966 },
  { title: "Forrest Gump", year: 1994 },
  { title: "Fight Club", year: 1999 },
  { title: "The Lord of the Rings: The Two Towers", year: 2002 },
  { title: "Inception", year: 2010 },
  { title: "Star Wars: A New Hope", year: 1977 },
  { title: "The Matrix", year: 1999 },
  { title: "Goodfellas", year: 1990 },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
  { title: "Seven Samurai", year: 1954 },
  { title: "Se7en", year: 1995 },

  { title: "City of God", year: 2002 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "Life Is Beautiful", year: 1997 },
  { title: "The Green Mile", year: 1999 },
  { title: "Interstellar", year: 2014 },
  { title: "Parasite", year: 2019 },
  { title: "Léon: The Professional", year: 1994 },
  { title: "The Usual Suspects", year: 1995 },
  { title: "The Lion King", year: 1994 },

  { title: "Back to the Future", year: 1985 },
  { title: "The Pianist", year: 2002 },
  { title: "Terminator 2: Judgment Day", year: 1991 },
  { title: "American History X", year: 1998 },
  { title: "Modern Times", year: 1936 },
  { title: "Gladiator", year: 2000 },
  { title: "The Departed", year: 2006 },
  { title: "Whiplash", year: 2014 },
  { title: "The Prestige", year: 2006 },
  { title: "The Intouchables", year: 2011 },

  { title: "The Dark Knight Rises", year: 2012 },
  { title: "Alien", year: 1979 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "Memento", year: 2000 },
  { title: "Raiders of the Lost Ark", year: 1981 },
  { title: "Django Unchained", year: 2012 },
  { title: "WALL-E", year: 2008 },
  { title: "The Shining", year: 1980 },
  { title: "Avengers: Infinity War", year: 2018 },
  { title: "Oldboy", year: 2003 },

  { title: "Princess Mononoke", year: 1997 },
  { title: "Aliens", year: 1986 },
  { title: "Once Upon a Time in the West", year: 1968 },
  { title: "Coco", year: 2017 },
  { title: "American Beauty", year: 1999 },
  { title: "Braveheart", year: 1995 },
  { title: "Toy Story", year: 1995 },
  { title: "Amadeus", year: 1984 },
  { title: "A Clockwork Orange", year: 1971 },
  { title: "Taxi Driver", year: 1976 },

  { title: "The Social Network", year: 2010 },
  { title: "Full Metal Jacket", year: 1987 },
  { title: "The Grand Budapest Hotel", year: 2014 },
  { title: "Jurassic Park", year: 1993 },
  { title: "The Terminator", year: 1984 },
  { title: "Jaws", year: 1975 },
  { title: "Blade Runner", year: 1982 },
  { title: "Gone with the Wind", year: 1939 },
  { title: "Die Hard", year: 1988 },
  { title: "The Wolf of Wall Street", year: 2013 },

  { title: "No Country for Old Men", year: 2007 },
  { title: "Shutter Island", year: 2010 },
  { title: "The Big Lebowski", year: 1998 },
  { title: "Mad Max: Fury Road", year: 2015 },
  { title: "Dead Poets Society", year: 1989 },
  { title: "Logan", year: 2017 },
  { title: "There Will Be Blood", year: 2007 },
  { title: "The Truman Show", year: 1998 },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
  { title: "Groundhog Day", year: 1993 },

  { title: "Donnie Darko", year: 2001 },
  { title: "La La Land", year: 2016 },
  { title: "Joker", year: 2019 },
  { title: "1917", year: 2019 },
  { title: "The Irishman", year: 2019 },

  { title: "The Sixth Sense", year: 1999 },
  { title: "Stand by Me", year: 1986 },
  { title: "Platoon", year: 1986 },
  { title: "Rain Man", year: 1988 },
  { title: "Rocky", year: 1976 },
  { title: "Scarface", year: 1983 },
  { title: "The Exorcist", year: 1973 },
  { title: "Fargo", year: 1996 },
  { title: "The Thing", year: 1982 },
  { title: "Heat", year: 1995 },

  { title: "Casino", year: 1995 },
  { title: "The Revenant", year: 2015 },
  { title: "The Sting", year: 1973 },
  { title: "Network", year: 1976 },
  { title: "Ben-Hur", year: 1959 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "The Elephant Man", year: 1980 },
  { title: "Amélie", year: 2001 },
  { title: "Snatch", year: 2000 },
  { title: "Lock, Stock and Two Smoking Barrels", year: 1998 },

  { title: "The Incredibles", year: 2004 },
  { title: "Finding Nemo", year: 2003 },
  { title: "Inside Out", year: 2015 },
  { title: "Up", year: 2009 },
  { title: "Monsters, Inc.", year: 2001 },
  { title: "Shrek", year: 2001 },
  { title: "Ratatouille", year: 2007 },
  { title: "My Neighbor Totoro", year: 1988 },
  { title: "The Iron Giant", year: 1999 },
  { title: "Kung Fu Panda", year: 2008 },

  { title: "Harry Potter and the Sorcerer's Stone", year: 2001 },
  { title: "Harry Potter and the Chamber of Secrets", year: 2002 },
  { title: "Harry Potter and the Prisoner of Azkaban", year: 2004 },
  { title: "Harry Potter and the Goblet of Fire", year: 2005 },
  { title: "Harry Potter and the Order of the Phoenix", year: 2007 },
  { title: "Harry Potter and the Half-Blood Prince", year: 2009 },
  { title: "Harry Potter and the Deathly Hallows – Part 1", year: 2010 },
  { title: "Harry Potter and the Deathly Hallows – Part 2", year: 2011 },

  { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003 },
  { title: "Avatar", year: 2009 },
  { title: "Titanic", year: 1997 },
  { title: "The Hunger Games", year: 2012 },
  { title: "Catching Fire", year: 2013 },
  { title: "Skyfall", year: 2012 },

  { title: "Casino Royale", year: 2006 },
  { title: "GoldenEye", year: 1995 },
  { title: "From Russia with Love", year: 1963 },
  { title: "Goldfinger", year: 1964 },
  { title: "Dr. No", year: 1962 },

  { title: "Raging Bull", year: 1980 },
  { title: "The Deer Hunter", year: 1978 },
  { title: "Unforgiven", year: 1992 },
  { title: "Chinatown", year: 1974 },
  { title: "Dog Day Afternoon", year: 1975 },

  { title: "Blade Runner 2049", year: 2017 },
  { title: "Her", year: 2013 },
  { title: "Moonlight", year: 2016 },
  { title: "The Shape of Water", year: 2017 },
  { title: "Birdman", year: 2014 },

  { title: "Slumdog Millionaire", year: 2008 },
  { title: "Million Dollar Baby", year: 2004 },
  { title: "Argo", year: 2012 },
  { title: "Spotlight", year: 2015 },
  { title: "The King's Speech", year: 2010 },

  { title: "A Beautiful Mind", year: 2001 },
  { title: "The Artist", year: 2011 },
  { title: "Bohemian Rhapsody", year: 2018 },
  { title: "The Imitation Game", year: 2014 },

  { title: "Arrival", year: 2016 },
  { title: "Ex Machina", year: 2014 },
  { title: "Children of Men", year: 2006 },
  { title: "Gattaca", year: 1997 },

  { title: "Planet of the Apes", year: 1968 },
  { title: "The Terminator", year: 1984 },
  { title: "Predator", year: 1987 },
  { title: "Robocop", year: 1987 },

  { title: "Rocky II", year: 1979 },
  { title: "Rocky III", year: 1982 },
  { title: "Rocky IV", year: 1985 },
  { title: "Creed", year: 2015 },
  { title: "Ford v Ferrari", year: 2019 },

  { title: "Ocean's Eleven", year: 2001 },
  { title: "Drive", year: 2011 },
  { title: "Baby Driver", year: 2017 },
  { title: "Zodiac", year: 2007 },
  { title: "Gone Girl", year: 2014 },

  { title: "The Big Short", year: 2015 },
  { title: "Catch Me If You Can", year: 2002 },
  { title: "Once Upon a Time in Hollywood", year: 2019 },

  { title: "E.T. the Extra-Terrestrial", year: 1982 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "Schindler's List", year: 1993 },

  { title: "The Fugitive", year: 1993 },
  { title: "The Rock", year: 1996 },
  { title: "Speed", year: 1994 },

  { title: "Mission: Impossible", year: 1996 },
  { title: "Mission: Impossible – Fallout", year: 2018 },

  { title: "Ghostbusters", year: 1984 },
  { title: "Men in Black", year: 1997 },

  { title: "Cast Away", year: 2000 },
  { title: "The Terminal", year: 2004 },

  { title: "Spider-Man", year: 2002 },
  { title: "Iron Man", year: 2008 },

  { title: "The Avengers", year: 2012 },
  { title: "Avengers: Endgame", year: 2019 },

  { title: "Guardians of the Galaxy", year: 2014 },
  { title: "Doctor Strange", year: 2016 },
  { title: "Black Panther", year: 2018 },

  { title: "Captain Marvel", year: 2019 }
];

